unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: 0
log: 1
element_name: url
time_limit: '5'
expire: 300
form_settings:
  user_register_form: 1
  user_pass: 0
  node_type_node_form: 0
  comment_comment_form: 0
langcode: nb
