patterns:
  node:
    default: 'content/[node:title]'
    bundles:
      article:
        default: ''
      featured_speaker:
        default: ''
      page:
        default: ''
      session:
        default: 'session/[node:title]'
      sponsor:
        default: ''
  taxonomy_term:
    default: '[term:vocabulary]/[term:name]'
    bundles:
      experience_level:
        default: ''
      sponsor_level:
        default: ''
      tags:
        default: ''
  forum:
    default: '[term:vocabulary]/[term:name]'
  user:
    default: 'users/[user:name]'
