language: php
php:
- 7.0
env:
  global:
  - DATABASE='drupal'
  - DB_USERNAME='root'
  - DB_ENCODE='utf8'
mysql:
  database: "$DATABASE"
  username: "$DB_USERNAME"
  encoding: "$DB_ENCODE"
before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version
  - mysql -e "create database IF NOT EXISTS test;" -uroot
install:
  - composer --verbose install
  - cd $TRAVIS_BUILD_DIR/web
  - chmod -R 777 sites/default
  - touch sites/default/settings.local.php
  - ./../vendor/bin/drush site-install minimal --verbose --yes --db-url=mysql://root@127.0.0.1/test
  - ./../vendor/bin/drush cset system.site uuid ffb6d131-689a-415d-a300-0af2e090ef1e -y
before_script:
  - ./../vendor/bin/drush cim --verbose --yes
  - ./../vendor/bin/drush updb --verbose --yes
  - ./../vendor/bin/drush cr
  - ./../vendor/bin/drush runserver http://127.0.0.1:8888 &
  - sleep 3
script:
  - composer test
