unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: true
element_name: url
time_limit: 0
expire: 300
form_settings:
  user_register_form: true
  user_pass: false
  node_type_node_form: false
langcode: nb
