label: 'Siste kommentarer'
display:
  default:
    display_title: Hoved
    display_options:
      title: 'Siste kommentarer'
      empty:
        area_text_custom:
          content: 'Ingen kommentarer tilgjengelige.'
  block_1:
    display_title: Blokk
    display_options:
      block_description: 'Siste kommentarer'
