display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
      fields:
        title:
          label: Tittel
        name:
          label: Forfatter
        changed:
          label: 'Siste oppdatering'
  attachment_1:
    display_title: Vedlegg
  page_1:
    display_title: Side
