label: 'Siste innlegg'
display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
      fields:
        edit_node:
          text: Rediger
        delete_node:
          text: Slett
      title: 'Siste innlegg'
      empty:
        area_text_custom:
          content: 'Intet innhold tilgjengelig.'
      use_more_text: Mer
  block_1:
    display_title: Blokk
