label: Filer
display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
      fields:
        filename:
          label: Navn
        filesize:
          label: Størrelse
        status:
          label: Status
        count:
          label: 'Brukt i'
      filters:
        filename:
          expose:
            label: Filnavn
        status:
          expose:
            label: Status
      title: Filer
  page_1:
    display_options:
      menu:
        title: Filer
  page_2:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
      fields:
        entity_label:
          label: Entitet
        type:
          label: Entitetstype
        count:
          label: 'Antall ganger brukt'
          format_plural_singular: '1'
      arguments:
        fid:
          exception:
            title: Alle
